plugins {
    id 'com.github.johnrengelman.shadow'
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

loom {
    mixin {
        useLegacyMixinAp = false
    }
    runs {
        configureEach {
            property 'yes_steve_model.debug.disable_lan_auth', 'true'
        }

        client2 {
            client()
            runDir 'run/client_b'
            programArgs '--username', 'gushroom'
        }
    }
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    neoForge "net.neoforged:neoforge:$rootProject.neo_version"

    modImplementation "dev.architectury:architectury-neoforge:$rootProject.architectury_api_version"
    include "dev.architectury:architectury-neoforge:$rootProject.architectury_api_version"

    forgeRuntimeLibrary "com.github.TartaricAlkaline:ImageStream:-SNAPSHOT"
    include "com.github.TartaricAlkaline:ImageStream:-SNAPSHOT"

    forgeRuntimeLibrary "com.github.luben:zstd-jni:$rootProject.zstd_jni_version"
    include "com.github.luben:zstd-jni:$rootProject.zstd_jni_version"

    common(project(path: ':common', configuration: 'namedElements')) { transitive false }
    shadowBundle project(path: ':common', configuration: 'transformProductionNeoForge')
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/neoforge.mods.toml') {
        expand version: project.version,
                minecraft_version: rootProject.minecraft_version,
                neo_version: rootProject.neo_version
    }

    from(project(':common').sourceSets.main.resources) {
        exclude 'yes_steve_model.mixins.json'
    }
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    input.set shadowJar.archiveFile
}
