{
  "formatVersion": "1.1",
  "component": {
    "group": "net.neoforged",
    "module": "neoforge",
    "version": "21.1.229",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neoforge-21.1.229-sources.jar",
          "url": "neoforge-21.1.229-sources.jar",
          "size": 1777578,
          "sha512": "604237b649d8f2f2fac5f750bf9e55dddd08f2770703360f25855733afc6650100caed01f801c9b9f0a926a8d60c3318c29a7a9c2a2e0cf3a14de3cbb34f8183",
          "sha256": "bfaa8d3653c180ccda4864ba9b9127e0f6c6f9bc6bde3cf40c78f90cc00cccc0",
          "sha1": "0923ddb9955687232bd07d39042c00bfebe951f7",
          "md5": "f42f702552db2eb2ef3544a2cccf9aa6"
        }
      ]
    },
    {
      "name": "modDevBundle",
      "attributes": {
        "org.gradle.category": "data",
        "org.gradle.dependency.bundling": "external"
      },
      "dependencies": [
        {
          "group": "net.neoforged",
          "module": "neoform",
          "version": {
            "requires": "1.21.1-20240808.144430"
          },
          "requestedCapabilities": [
            {
              "group": "net.neoforged",
              "name": "neoform"
            }
          ],
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "neoforge-21.1.229-userdev.jar",
          "url": "neoforge-21.1.229-userdev.jar",
          "size": 3979498,
          "sha512": "85a0b0e0d4313a9656cb5157fef23b665084f26ca6b65611b8d292b1193052a1e207b1af78d6059eedc518c5d2cd653fc52e3da7930bd525bce641b697bc8d7b",
          "sha256": "9e3fff5f6429aaa010366759fcd89326e8877a3e60789957babccb07b609adaf",
          "sha1": "9b368ca088b9e1ab3fbdb5313a3aaad398a60063",
          "md5": "9ce68011f22884714239ceddb8f87de0"
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-moddev-bundle",
          "version": "21.1.229"
        }
      ]
    },
    {
      "name": "modDevConfig",
      "attributes": {
        "org.gradle.category": "data",
        "org.gradle.dependency.bundling": "external"
      },
      "files": [
        {
          "name": "neoforge-21.1.229-moddev-config.json",
          "url": "neoforge-21.1.229-moddev-config.json",
          "size": 10209,
          "sha512": "5532628bcc3ef0ddc88819543faeb695b16569c82042b0b7fcb96d9e273e64f66bac3050206cd46d0ad923b449aa09c11544949bc039ea9f8e52b9f0835e85bd",
          "sha256": "add8d6c54defa6cc1c09a09bbc6df8998eba77eecddaedf271156f9fefbf2a99",
          "sha1": "24cadeeb82920307190a44cd1826d5a24400a173",
          "md5": "e87648a4393bf2d272d0cc28d028b711"
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-moddev-config",
          "version": "21.1.229"
        }
      ]
    },
    {
      "name": "installerJar",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neoforge-21.1.229-installer.jar",
          "url": "neoforge-21.1.229-installer.jar",
          "size": 6961796,
          "sha512": "b9402b7df919c36464beb7be4769316a0c270909931c06a0e571752221148244355b8e28a028542e0fad2ecc8db6c92ac9340884b27ff639d1715a8e4cbbc2d4",
          "sha256": "856856cb96f9563a2565924268d926b09a8704b9c4963469736110fb4b6a5920",
          "sha1": "7b6f8512bb5f6a2c5d83e3385016da9813d3589b",
          "md5": "4b60d7fb2b293144f04117634936548f"
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-installer",
          "version": "21.1.229"
        }
      ]
    },
    {
      "name": "universalJar",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neoforge-21.1.229-universal.jar",
          "url": "neoforge-21.1.229-universal.jar",
          "size": 3531240,
          "sha512": "cd2eb02c310dd3b89630040565dfd23d2d7e9f8b30736ce50eb140bb4f32e59f1644cb6d22ff1147de99640840d74a8f5508ea6cf241fc51896542701083ab49",
          "sha256": "f8da762ae567b0a13d751a07a251ae832206a6c28ab8aebb787535c5945b53b7",
          "sha1": "49e229918ee4fcf953eb3ddde0b6773cb0ec2b3d",
          "md5": "1002c0518fd7ad7f899606942a999094"
        }
      ]
    },
    {
      "name": "changelog",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.docstype": "changelog"
      },
      "files": [
        {
          "name": "neoforge-21.1.229-changelog.txt",
          "url": "neoforge-21.1.229-changelog.txt",
          "size": 45764,
          "sha512": "9db8dd2beacfaaccbc88947499679f63829efe7da4efd2feab66a972363691f22c04d518e4bc87602bd7d5c104365ff1374c2958ced6c4f8ba8c9de13cf956ba",
          "sha256": "f199d6740210a839249722e0a42466ea808755b4e2b8dedf66451b52181d9673",
          "sha1": "09ea861afb17de07b6db6cc44f1e228b094c9964",
          "md5": "77a182f89b79519176f5c3346ca3abab"
        }
      ]
    },
    {
      "name": "modDevApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.neoforged.fancymodloader",
          "module": "loader",
          "version": {
            "requires": "4.0.42"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.fancymodloader",
          "module": "earlydisplay",
          "version": {
            "requires": "4.0.42"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            },
            {
              "group": "org.lwjgl",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "accesstransformers",
          "version": {
            "requires": "10.0.1"
          }
        },
        {
          "group": "net.neoforged",
          "module": "bus",
          "version": {
            "requires": "8.0.5"
          }
        },
        {
          "group": "net.neoforged",
          "module": "coremods",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "cpw.mods",
          "module": "modlauncher",
          "version": {
            "requires": "11.0.5"
          }
        },
        {
          "group": "net.neoforged",
          "module": "mergetool",
          "version": {
            "requires": "2.0.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mergetool",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.8.5"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "sponge-mixin",
          "version": {
            "requires": "0.15.2+mixin.0.8.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.openjdk.nashorn",
          "module": "nashorn-core",
          "version": {
            "requires": "15.4"
          }
        },
        {
          "group": "net.neoforged",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "net.neoforged",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "cpw.mods",
          "module": "securejarhandler",
          "version": {
            "requires": "3.0.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "cpw.mods",
          "module": "bootstraplauncher",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "net.neoforged",
          "module": "JarJarFileSystems",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.5.3"
          }
        },
        {
          "group": "net.neoforged",
          "module": "neoform",
          "version": {
            "requires": "1.21.1-20240808.144430"
          },
          "requestedCapabilities": [
            {
              "group": "net.neoforged",
              "name": "neoform-dependencies"
            }
          ],
          "endorseStrictVersions": true
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-dependencies",
          "version": "21.1.229"
        }
      ]
    },
    {
      "name": "modDevRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.neoforged.fancymodloader",
          "module": "loader",
          "version": {
            "requires": "4.0.42"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.fancymodloader",
          "module": "earlydisplay",
          "version": {
            "requires": "4.0.42"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            },
            {
              "group": "org.lwjgl",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "accesstransformers",
          "version": {
            "requires": "10.0.1"
          }
        },
        {
          "group": "net.neoforged",
          "module": "bus",
          "version": {
            "requires": "8.0.5"
          }
        },
        {
          "group": "net.neoforged",
          "module": "coremods",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "cpw.mods",
          "module": "modlauncher",
          "version": {
            "requires": "11.0.5"
          }
        },
        {
          "group": "net.neoforged",
          "module": "mergetool",
          "version": {
            "requires": "2.0.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mergetool",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.8.5"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "sponge-mixin",
          "version": {
            "requires": "0.15.2+mixin.0.8.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.openjdk.nashorn",
          "module": "nashorn-core",
          "version": {
            "requires": "15.4"
          }
        },
        {
          "group": "net.neoforged",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "net.neoforged",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "cpw.mods",
          "module": "securejarhandler",
          "version": {
            "requires": "3.0.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "cpw.mods",
          "module": "bootstraplauncher",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "net.neoforged",
          "module": "JarJarFileSystems",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.neoforged",
          "module": "neoform",
          "version": {
            "requires": "1.21.1-20240808.144430"
          },
          "requestedCapabilities": [
            {
              "group": "net.neoforged",
              "name": "neoform-dependencies"
            }
          ],
          "endorseStrictVersions": true
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-dependencies",
          "version": "21.1.229"
        }
      ]
    },
    {
      "name": "modDevModulePath",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external"
      },
      "dependencies": [
        {
          "group": "cpw.mods",
          "module": "securejarhandler",
          "version": {
            "requires": "3.0.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "cpw.mods",
          "module": "bootstraplauncher",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "net.neoforged",
          "module": "JarJarFileSystems",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-moddev-module-path",
          "version": "21.1.229"
        }
      ]
    },
    {
      "name": "modDevTestFixtures",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.neoforged.fancymodloader",
          "module": "junit-fml",
          "version": {
            "requires": "4.0.42"
          },
          "endorseStrictVersions": true
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-moddev-test-fixtures",
          "version": "21.1.229"
        }
      ]
    }
  ]
}
